name: Prettier

on:
    workflow_dispatch


jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
          - uses: pnpm/action-setup@v3
            with:
              run_install: |
                - args: [--frozen-lockfile]
          - name: Run Prettier
            run: pnpm exec prettier --write .
