name: Open release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prepare release with Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          title: Release
          commit: Release
          publish: "pnpm publish:ci"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Trigger other workflow
        if: steps.changesets.outputs.hasChangesets == 'true'
        # You can do something when a publish should happen.
        run: echo "Changesets to publish"
