name: Open release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prepare release with Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          title: Release
          commit: Release
          publish: "pnpm publish:ci"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger other workflow
        if: steps.changesets.outputs.published == 'false'
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ steps.changesets.outputs.pullRequestNumber }}
          body: |
            Body comment
